# Site
name: 'On Knowing' 
description: 'The practical application of epistemology to advance how we learn, understand and create things.' 
logo: 'assets/images/Night-Owl.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://www.OnKnowing.com'
# disqus: 'demowebsite'
email: 'info@OnKnowing.com' 
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jamie:
      name:           Jamie
      site:           https://www.ResearchOnKnowing.com
      avatar:         assets/images/Jamie.jpg 
      bio:            "Hi, I'm Jamie, an author here at On Knowing. I hope these posts add to your understand of what knowledge is!"
      email:          jamie@OnKnowing.com
      twitter:        https://twitter.com/JamieOnKnowing
    dan:
      name:           Dan
      site:           https://www.Dans-IT-Cookbook.com
      avatar:         assets/images/Dan.jpg 
      bio:            "Hi, I'm Dan, an author here at On Knowing. I hope these posts add to your understand of what knowledge is!"
      email:          dan@OnKnowing.com
      twitter:        https://twitter.com/Dan_IT_Cookbook


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jamie
      avatar: /assets/images/Jamie.jpg 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]